# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 팀블로그 (AIBT)
email: jgbossassa@iabacus.co.kr
description: >- # this means to ignore newlines until "baseurl:"
  우리팀의 발자취를 다시 눈속으로 사라지게 하는 것보다 사진을 찍어서 남기고 싶습니다.
  많은것을 도전하고 있고, 이를 하나 둘 씩 히스토리로 남겨보고 싶습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: j
github_username:  socketbear

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - github-pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
